### ISSUE TITLE
Criar mecanismo de drag and drop

### ISSUE THREAD

**Issue by jaimerson** [jaimerson/laboratorio_de_palavras#10]
Criar mecanismo de drag and drop onde elementos podem ser arrastados e soltos em um determinado espaço. Se o elemento for arrastado e solto fora do local designado, deve voltar a sua posição inicial.

**Comment by arthurcohen** [comment]
@joanun3s2 , saca só
https://pixijs.io/examples/#/interaction/dragging.js

**Comment by elisales** [comment]
Ainda utilizarão o Drag and Drop ou essa Issue foi sanada?

**Comment by jaimerson** [comment]
@elisales ainda está aberta porque foi pra a categoria "se der tempo" ou "baixa prioridade"
