### ISSUE TITLE
Teste da utilização de Vue em conjunto com o PIXI

### ISSUE THREAD

**Issue by jaimerson** [jaimerson/laboratorio_de_palavras#2]
Verificar se o projeto fica melhor organizado utilizando Vue para fazer as transições entre os diferentes estados do jogo.

**Comment by jaimerson** [comment]
@MrBlack11 vai rolar ou a gente fecha essa issue?

**Comment by MrBlack11** [comment]
Estou vendo como comporta o vue com electron, e te mando o exemplo que vou criar.

**Comment by arthurcohen** [comment]
@MrBlack11 teve algum sucesso até então? Tá quebrando em algum lugar?
Compartilha com a gente depois onde você está atuando pra ver se ajudamos.

**Comment by MrBlack11** [comment]
Criei um projeto usando vue + electron, e vi que fica mais tranquilo trabalhar com vue e criar componentes para o pixi (dependendo da necessidade, a nossa provavelmente é utilizar drag and drop).
