### ISSUE TITLE
Commit da Branch do Daniel

### ISSUE THREAD

**Issue by elisales** [jaimerson/laboratorio_de_palavras#23]
Pessoal, 
Fico pertubando vocês para atualizar a branch principal porque é importantíssimo para perspectiva de software livre. Então, tentem o quanto antes, atualizar a branch principal com o projeto que vocês levaram como base. 
Ai estando na principal, os membros do grupo criam, ajustam e atualizam.

**Comment by jaimerson** [comment]
Atualizada
