### ISSUE TITLE
Adição das frases restantes

### ISSUE THREAD

**Issue by jaimerson** [jaimerson/laboratorio_de_palavras#33]
Existem mais frases que ainda não estão nesse repositório.
As imagens estão na pasta `rabiscos` no google drive. Elas devem ser adicionadas aqui em `assets/results`. Os nomes de arquivos não devem conter espaço. As frases devem ser cadastradas em `config/sentence.yml`. *TESTAR TODAS AS FRASES E SUAS IMAGENS*.

**Comment by MrBlack11** [comment]
Caminho correto: src/repositories/sentence_repository.ts
