### ISSUE TITLE
Criação da fase principal

### ISSUE THREAD

**Issue by jaimerson** [jaimerson/laboratorio_de_palavras#4]
O Jogador deve poder visualizar a frase, faltando os pedaços configurados e clicar nas palavras disponíveis que irão para dentro dos espaços. Ao colocar todas as palavras nos espaços, deve aparecer o botão de finalizar.

**Comment by MrBlack11** [comment]
@italovieira Como está a tela do game? Vc já conseguiu iniciar?

**Comment by italovieira** [comment]
@MrBlack11 Ainda não.

**Comment by italovieira** [comment]
Tentei dar uma mexida, mas tô com problemas para iniciar o projeto:
![image](https://user-images.githubusercontent.com/8337230/68892575-144ad900-0702-11ea-98d7-48327ad7adef.png)

Alterei o caminho nos arquivos que aponta para as imagens, mas não foi.

**Comment by italovieira** [comment]
Tava com problema para compilar o projeto. Corrigi, mas acabou que não deu tempo.

**Comment by MrBlack11** [comment]
O @jaimerson já corrigiu os problemas e colocou na master. Estou terminando a parte funcional da tela do jogo, vai ficar só interface pra vc @italovieira.

**Comment by italovieira** [comment]
@MrBlack11 Tranquilo!

**Comment by jaimerson** [comment]
Closed in #29
