### ISSUE TITLE
Utilização de frases cadastradas na fase principal

### ISSUE THREAD

**Issue by jaimerson** [jaimerson/laboratorio_de_palavras#5]
As frases definidas no SGDD pela equipe pedagógica devem ser postas no arquivo `config/sentences.yml`. Por enquanto somente as de troca de substantivos.

**Comment by jaimerson** [comment]
Blocked by #1

**Comment by arthurcohen** [comment]
Vou estar subindo um complemento a issue #1 no pr #13 que auxiliará quem for atuar nessa tarefa.

**Comment by joanun3s2** [comment]
Arquivo feito, so checando pra possíveis atualizações.

**Comment by jaimerson** [comment]
Valeu @joanun3s2. Fechada em #29 .
