### ISSUE TITLE
Criação da tela de resultados

### ISSUE THREAD

**Issue by jaimerson** [jaimerson/laboratorio_de_palavras#6]
Quando o jogador montar sua frase e clicar em OK, deve ser levado à tela de resultados. Essa tela deve conter a frase formada, a imagem associada ao resultado e os botões de jogar novamente e sair para o menu.

**Comment by babbujah** [comment]
Boa tarde galera.
Seguinte:
Estou estudando pelo tutorial disponível na página do Pixijs. Eu fiz uns testes e simulações, todas em ambiente web. Consegui adicionar alguns sprites e para o contexto desta tarefa, acredito que dá para adicionar alguma coisa.
Mas agora começa as frutações, choro e lamentações.
No tutorial, estou na parte onde podemos carregar a partir de um atlas de textura. Usei o Texture packer para gerar meu atlas de modelo de teste. Assim, foi adicionado um arquivo .json para poder separar os frames dos sprites a serem utilizados no ambiente. Mas, nesse ponto, não estou conseguindo exibir nada na página. Ainda não consegui descobrir o motivo.
Outra bronca é que percebi que  o atlas de textura é estático. Seria necessário que a galera de design desenhasse as figuras em seus tamanhos padrão para podermos utilizar. Não sei se há alguma outra forma de construir esse atlas mais dinâmico.
Além disso, não vi nada sobre responsividade para serem aplicados nos cenários do jogo (nossas telas).

**Comment by babbujah** [comment]
O código está abaixo:
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<title>Hello World</title>
</head>
<script type="pixi/pixi.min.js"></script>
<body>
	<script type="text/javascript">
		let type = "WebGL"
		let utils = PIXI.utils
		if( !utils.isWebGLSupported() ){
			type = "canvas"
		}

		utils.sayHello( type )		

		// Create a Pixi Application
		let Application = PIXI.Application
		let app = new Application({
			width: 256,
			height: 256,
			antialias: true,
			transparent: false,
			resolution: 1
		});

		//Add the canvas that Pixi automatically created for you the HTML document
		document.body.appendChild( app.view );

		renderer = app.renderer
		renderer.backgroundColor = 0x061639;
		renderer.autoResize = true;
		renderer.resize( 512, 512 );
		renderer.view.style.position = "absolute";
		renderer.view.style.display = "block";
		renderer.autoResize = true;
		renderer.resize( window.innerWidth, window.innerHeight );

		loader = PIXI.loader
		loader
			.add( "images/treasureHunter.json" )
			.load( setup );

		// Define variables that might be used in more than one function
		let dungeon, explorer, treasure, id;

		function setup(){
			// There are 3 ways to make sprites from texture atlas frames

			// 1. Access the 'TextureCache' directly
			TextureCache = PIXI.utils.TextureCache
			let dungeonTexture = TextureCache["dungeon.png"];
			Sprite = PIXI.Sprite
			dungeon = new Sprite( dungeonTexture );
			app.stage.addChild( dungeon );

			//2. Access the texture using through the loader's 'resources'
			let resources = PIXI.loader.resources;
			explorer = new Sprite( resources["images/treasureHunter.json"].textures["explorer.png"] );
			explorer.x = 68;
			// Center explorer vertically
			explorer.y = app.stage.height / 2 - explorer.height / 2;
			app.stage.addChild( explorer );

			// 3. Create an optional alias called 'id' for all the texture atlas frame id textures.
			id = resources["images/treasureHunter.json"].textures;

			// Make the treasure box using the alias
			treasure = new Sprite( id["treasure.png"] );
			app.stage.addChild( treasure );

			//Position the treasure next to the right edge of the canvas
			treasure.x = app.stage.width - treasure.width - 48;
			treasure.y = app.stage.height / 2 - treasure.height / 2;
			app.stage.addChild(treasure);

			// Render the stage
			app.renderer.render( app.stage );
		}

	</script>
	<style>* {padding: 0; margin: 0}</style>

</body>
</html>

**Comment by jaimerson** [comment]
@babbujah vou testar localmente e te ajudo segunda no máximo

**Comment by babbujah** [comment]
Bom dia galera.
Consegui resolver a questão de não está sendo gerado os sprites. Eu estava fazendo algo bem estúpido (rsrsrs). Ao invés de escrever:
<script src="pixi/pixi.min.js"></script>

estava fazendo:
<script type="pixi/pixi.min.js"></script>

Assim o arquivo não estava sendo reconhecido.
Ainda continuam os problemas de responsividade e imagens estáticas.

**Comment by jaimerson** [comment]
Funcionalidade finalizada em #29
